name: MLXClaw
options:
  bundleIdPrefix: com.mlx
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  Starscream:
    url: https://github.com/daltoniam/Starscream
    from: "4.0.0"

targets:
  MLXClaw:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: Starscream

schemes:
  MLXClaw:
    build:
      targets:
        MLXClaw: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
